### PR TITLE
ELMU-24 Update educandu to v0.8.0

### PR DESCRIPTION
**Pull request by ahelmberger**
Closes https://educandu.atlassian.net/browse/ELMU-24

### CODE REVIEW

**Comment by adrianaluchian** [comment]
Was thinking just now as I ran this locally, should we maybe set `disabledFeatures` as `JSON.parse(processEnv.ELMU_DISABLED_FEATURES || '['rooms']')` so that we don't see this feature when we run ELMU locally? 🤔

**Comment by ahelmberger** [comment]
> Was thinking just now as I ran this locally, should we maybe set `disabledFeatures` as `JSON.parse(processEnv.ELMU_DISABLED_FEATURES || '['rooms']')` so that we don't see this feature when we run ELMU locally? thinking

Maybe, but maybe we could also invert the way we toggle features (making it an `enabledFeatures`). That reflects more our usage (things being toggled off by default)?

**Comment by adrianaluchian** [comment]
> > Was thinking just now as I ran this locally, should we maybe set `disabledFeatures` as `JSON.parse(processEnv.ELMU_DISABLED_FEATURES || '['rooms']')` so that we don't see this feature when we run ELMU locally? thinking
> 
> Maybe, but maybe we could also invert the way we toggle features (making it an `enabledFeatures`). That reflects more our usage (things being toggled off by default)?

I guess it depends on each feature toggle. When we introduced the one for `imports`, the idea of these toggles was to temporarily disable features until we bring them live. Then we introduced `rooms` which is temporarily disabled for OMA (maybe) and permanently for ELMU.

In my opinion, we should keep the `disabledFeatures` naming also because we wouldn't want to end up with a huge list of features in there, once we bring them live and are there to stay.

**Comment by ahelmberger** [comment]
> > > Was thinking just now as I ran this locally, should we maybe set `disabledFeatures` as `JSON.parse(processEnv.ELMU_DISABLED_FEATURES || '['rooms']')` so that we don't see this feature when we run ELMU locally? thinking
> > 
> > 
> > Maybe, but maybe we could also invert the way we toggle features (making it an `enabledFeatures`). That reflects more our usage (things being toggled off by default)?
> 
> I guess it depends on each feature toggle. When we introduced the one for `imports`, the idea of these toggles was to temporarily disable features until we bring them live. Then we introduced `rooms` which is temporarily disabled for OMA (maybe) and permanently for ELMU.
> 
> In my opinion, we should keep the `disabledFeatures` naming also because we wouldn't want to end up with a huge list of features in there, once we bring them live and are there to stay.

Yeah, the rooms toggle is actually a configuration, not a temporary toggle, I agree. Let's discuss this as an extra subject, ok? Because I think there's more to it (e.g. not starting the processor loop in case import is disabled). Unless it bothers you too much seeing that entry locally :smile:

**Comment by adrianaluchian** [comment]
> > > > Was thinking just now as I ran this locally, should we maybe set `disabledFeatures` as `JSON.parse(processEnv.ELMU_DISABLED_FEATURES || '['rooms']')` so that we don't see this feature when we run ELMU locally? thinking
> > > 
> > > 
> > > Maybe, but maybe we could also invert the way we toggle features (making it an `enabledFeatures`). That reflects more our usage (things being toggled off by default)?
> > 
> > 
> > I guess it depends on each feature toggle. When we introduced the one for `imports`, the idea of these toggles was to temporarily disable features until we bring them live. Then we introduced `rooms` which is temporarily disabled for OMA (maybe) and permanently for ELMU.
> > In my opinion, we should keep the `disabledFeatures` naming also because we wouldn't want to end up with a huge list of features in there, once we bring them live and are there to stay.
> 
> Yeah, the rooms toggle is actually a configuration, not a temporary toggle, I agree. Let's discuss this as an extra subject, ok? Because I think there's more to it (e.g. not starting the processor loop in case import is disabled). Unless it bothers you too much seeing that entry locally 😄

Sure thing, we'll discuss separately then.

**Review by adrianaluchian — APPROVED** [review]

**Pull request merged**
